from telethon import events
import random, re
from userbot.utils import admin_cmd
import asyncio


@borg.on(admin_cmd("fban ?(.*)"))
async def _(event):
    if event.fwd_from:
        return
    FBAN = event.pattern_match.group(1)
    chat = await event.get_chat()
    if not event.text[0].isalpha() and event.text[0] not in ("/", "#", "@", "!"):
        await borg.send_message(chat, f"/start")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 3f7aa34e-c5d3-459a-ba7a-0cbd16f518bc")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 25b7a645-fe4f-4ca3-a107-36ac659e80fd")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 28a1e5aa-6212-4874-b570-703c33587b98")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 50c9a837-7806-4c01-bae9-1804a3e6c7b0")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 5fcd2ae1-168d-4ce1-947e-95aabe05c331")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 622c3f70-0aa2-4376-9037-b091b0af8312")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed e19056a1-b488-4f19-a4b8-00e69fcbecbc")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 74dff8a0-e608-4c54-ba10-3e30fdf55ec9")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed dad7ebb6-6ada-4713-90ea-d617c6f54be1")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 0b7903bd-3297-4f48-b6f9-fe7869d59d5d")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 4bbde996-ad03-4378-8259-6da91624e53c")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(100)

@borg.on(admin_cmd("unfban ?(.*)"))
async def _(event):
    if event.fwd_from:
        return
    UNFBAN = event.pattern_match.group(1)
    chat = await event.get_chat()
    if not event.text[0].isalpha() and event.text[0] not in ("/", "#", "@", "!"):
        await borg.send_message(chat, f"/start")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 3f7aa34e-c5d3-459a-ba7a-0cbd16f518bc")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 25b7a645-fe4f-4ca3-a107-36ac659e80fd")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 28a1e5aa-6212-4874-b570-703c33587b98")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 50c9a837-7806-4c01-bae9-1804a3e6c7b0")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 5fcd2ae1-168d-4ce1-947e-95aabe05c331")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 622c3f70-0aa2-4376-9037-b091b0af8312")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed e19056a1-b488-4f19-a4b8-00e69fcbecbc")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 74dff8a0-e608-4c54-ba10-3e30fdf55ec9")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed dad7ebb6-6ada-4713-90ea-d617c6f54be1")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 0b7903bd-3297-4f48-b6f9-fe7869d59d5d")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(2)
        await borg.send_message(chat, "/joinfed 4bbde996-ad03-4378-8259-6da91624e53c")
        await asyncio.sleep(2)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(100)

